-------------------------
#### low-rank decomposition of a matrix
------------------------

In [1]:
import numpy as np

In [2]:
# Create a matrix (replace this with your actual matrix)
original_matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])

In [3]:
# Perform Singular Value Decomposition (SVD)
U, S, Vt = np.linalg.svd(original_matrix)

In [4]:
# Set the desired rank (replace this with your desired rank)
desired_rank = 2

In [5]:
# Truncate the matrices to achieve the desired rank
U_truncated = U[:, :desired_rank]
S_truncated = np.diag(S[:desired_rank])
Vt_truncated = Vt[:desired_rank, :]

In [6]:
# Reconstruct the low-rank decomposed matrix
low_rank_matrix = U_truncated @ S_truncated @ Vt_truncated

In [7]:
# Print the original and low-rank decomposed matrices
print("Original Matrix:")
print(original_matrix)
print("\nLow-Rank Decomposed Matrix:")
print(low_rank_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Low-Rank Decomposed Matrix:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
